### ISSUE TITLE
Spigotで、チャンク読み込みエラーが発生する

### ISSUE THREAD

**Issue by AhiruMarsh** [AhiruMarsh/lsmshub#2]
WSL2上で起動したコンテナー内のSpigot A/B サーバーで、2回目以降に起動したときに、
チャンクの読み込みエラーが発生する。

以下エラー詳細
> [IO-Worker-31/WARN]: Region file ./world_nether/DIM-1/region/r.0.-1.mca has an invalid sector at index: 498; sector 6644596 is out of bounds

> [IO-Worker-33/WARN]: Failed to read chunk [-6, 6]
> java.lang.IllegalArgumentException: Negative position
> 	at sun.nio.ch.FileChannelImpl.read(FileChannelImpl.java:789) ~[?:?]
> 	at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:91) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3379-Spigot-8965a50-0ba6b90]
> 	at net.minecraft.world.level.chunk.storage.RegionFile.<init>(RegionFile.java:49) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3379-Spigot-8965a50-0ba6b90]
> 	at net.minecraft.world.level.chunk.storage.RegionFileCache.getRegionFile(RegionFileCache.java:48) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3379-Spigot-8965a50-0ba6b90]
> 	at net.minecraft.world.level.chunk.storage.RegionFileCache.a(RegionFileCache.java:58) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3379-Spigot-8965a50-0ba6b90]
> 	at net.minecraft.world.level.chunk.storage.IOWorker.c(SourceFile:100) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3379-Spigot-8965a50-0ba6b90]
> 	at net.minecraft.world.level.chunk.storage.IOWorker.a(SourceFile:150) ~[spigot-1.18.1-R0.1-SNAPSHOT.jar:3379-Spigot-8965a50-0ba6b90]
> 	at net.minecraft.util.thread.PairedQueue$b.run(SourceFile:59) [spigot-1.18.1-R0.1-SNAPSHOT.jar:3379-Spigot-8965a50-0ba6b90]
> 	at net.minecraft.util.thread.ThreadedMailbox.g(SourceFile:91) [spigot-1.18.1-R0.1-SNAPSHOT.jar:3379-Spigot-8965a50-0ba6b90]
> 	at net.minecraft.util.thread.ThreadedMailbox.a(SourceFile:146) [spigot-1.18.1-R0.1-SNAPSHOT.jar:3379-Spigot-8965a50-0ba6b90]
> 	at net.minecraft.util.thread.ThreadedMailbox.run(SourceFile:102) [spigot-1.18.1-R0.1-SNAPSHOT.jar:3379-Spigot-8965a50-0ba6b90]
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
> 	at java.lang.Thread.run(Thread.java:833) 

WSL2上のコンテナーのみで発生か？

**Comment by AhiruMarsh** [comment]
おそらくDocker内の権限で読み取れないため、問題発生していると思われる。
解決できないかどうか模索のため、再オープン

**Comment by AhiruMarsh** [comment]
（https://sig9.hatenablog.com/entry/2020/02/19/000000）を参考
/etc/wsl.conf を作成
```shell
$ sudo cat /etc/wsl.conf
[automount]
options = "metadata"
```
optionsを書き込み
